export enum Enum1 {
  Val1 = 0,
  Val2 = 1,
  Val3 = 2,
}

export enum Enum2 {
  Val1 = 0,
  Val2 = 1,
  Val3 = 2,
}

export enum Enum3 {
  Val1 = 0,
  Val2 = 1,
  Val3 = 2,
  Val4 = 3,
  Val5 = 4,
}

export enum Enum4 {
  Val1 = 0,
  Val2 = 1,
  LongCar = 2,
}

export enum Enum5 {
  Val1 = 0,
  Val2 = 81,
  Val3 = 82,
  Val4 = 83,
  Val5 = 84,
  Val6 = 85,
}

export enum PalletIdentifier {
  Val1 = 0,
  Val2 = 255,
}

export interface Pallet {
  Prop1: Enum1;
  Prop2: Enum4;
  Prop3: string;
  Prop4: Enum2;
  Prop5: Enum3;
}

export enum PlcVariable {
  Var01 = 'GVL_Remote.Var01',
  Var02 = 'GVL_Remote.Var02',
  Var03 = 'GVL_Remote.Var03',
  Var04 = 'GVL_Remote.Var04',
  Var05 = 'GVL_Remote.Var05',
  Var06 = 'GVL_Remote.Var06',
  Var07 = 'GVL_Remote.Var07',
  Var08 = 'GVL_Remote.Var08',
  Var09 = 'GVL_Remote.Var09',
  Var10 = 'GVL_Remote.Var10',
  Var11 = 'GVL_Remote.Var11',
  Var12 = 'GVL_Remote.Var12',
  Var13 = 'GVL_Remote.Var13',
  Var14 = 'GVL_Remote.Var14',
  Var15 = 'GVL_Remote.Var15',
  Var16 = 'GVL_Remote.Var16',
  Var17 = 'GVL_Remote.Var17',
  Var18 = 'GVL_Remote.Var18',
  Var19 = 'GVL_Remote.Var19',
  Var20 = 'GVL_Remote.Var20',
  Var21 = 'GVL_Remote.Var21',
  Var22 = 'GVL_Remote.Var22',
  Var23 = 'GVL_Remote.Var23',
  Var24 = 'GVL_Remote.Var24',
  Var25 = 'GVL_Remote.Var25',
  Var26 = 'GVL_Remote.Var26',
  Var27 = 'GVL_Remote.Var27',
  Var28 = 'GVL_Remote.Var28',
  Var29 = 'GVL_Remote.Var29',
  Var30 = 'GVL_Remote.Var30',
  Var31 = 'GVL_Remote.Var31',
  Var32 = 'GVL_Remote.Var32',
  Var33 = 'GVL_Remote.Var33',
  Var34 = 'GVL_Remote.Var34',
  Var35 = 'GVL_Remote.Var35',
  Var36 = 'GVL_Remote.Var36',
  Var37 = 'GVL_Remote.Var37',
  Var38 = 'GVL_Remote.Var38',
  Var39 = 'GVL_Remote.Var39',
  Var40 = 'GVL_Remote.Var40',
  Var41 = 'GVL_Remote.Var41',
  Var42 = 'GVL_Remote.Var42',
  Var43 = 'GVL_Remote.Var43',
  Var44 = 'GVL_Remote.Var44',
  Var45 = 'GVL_Remote.Var45',
  Var46 = 'GVL_Remote.Var46',
}

export const PlcVariableDescriptions: Record<PlcVariable, string> = {
  [PlcVariable.Var01]: 'Var01',
  [PlcVariable.Var02]: 'Var02',
  [PlcVariable.Var03]: 'Var03',
  [PlcVariable.Var04]: 'Var04',
  [PlcVariable.Var05]: 'Var05',
  [PlcVariable.Var06]: 'Var06',
  [PlcVariable.Var07]: 'Var07',
  [PlcVariable.Var08]: 'Var08',
  [PlcVariable.Var09]: 'Var09',
  [PlcVariable.Var10]: 'Var10',
  [PlcVariable.Var11]: 'Var11',
  [PlcVariable.Var12]: 'Var12',
  [PlcVariable.Var13]: 'Var13',
  [PlcVariable.Var14]: 'Var14',
  [PlcVariable.Var15]: 'Var15',
  [PlcVariable.Var16]: 'Var16',
  [PlcVariable.Var17]: 'Var17',
  [PlcVariable.Var18]: 'Var18',
  [PlcVariable.Var19]: 'Var19',
  [PlcVariable.Var20]: 'Var20',
  [PlcVariable.Var21]: 'Var21',
  [PlcVariable.Var22]: 'Var22',
  [PlcVariable.Var23]: 'Var23',
  [PlcVariable.Var24]: 'Var24',
  [PlcVariable.Var25]: 'Var25',
  [PlcVariable.Var26]: 'Var26',
  [PlcVariable.Var27]: 'Var27',
  [PlcVariable.Var28]: 'Var28',
  [PlcVariable.Var29]: 'Var29',
  [PlcVariable.Var30]: 'Var30',
  [PlcVariable.Var31]: 'Var31',
  [PlcVariable.Var34]: 'Var34',
  [PlcVariable.Var32]: 'Var32',
  [PlcVariable.Var33]: 'Var33',
  [PlcVariable.Var35]: 'Var35',
  [PlcVariable.Var36]: 'Var36',
  [PlcVariable.Var37]: 'Var37',
  [PlcVariable.Var38]: 'Var38',
  [PlcVariable.Var39]: 'Var39',
  [PlcVariable.Var40]: 'Var40',
  [PlcVariable.Var41]: 'Var41',
  [PlcVariable.Var42]: 'Var42',
  [PlcVariable.Var43]: 'Var43',
  [PlcVariable.Var44]: 'Var44',
  [PlcVariable.Var45]: 'Var45',
  [PlcVariable.Var46]: 'Var46',
};

// This is an indexed list of all possible errors that can occur in the PLC.
// Indexes of messages in this array should be displayed when the a bit at the corresponding
// index in the Status_Tower_Errors array is set.
export const SystemErrors = [
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
  'Error Description',
]
